version: '3'
services:
	master:
		build:
	 		context: .
			dockerfile: ./docker/master.Dockerfile
		working_dir: /root/playbooks
		volumes:
			- ~/Documents/Ansible-env/playbooks:/root/playbooks
			- ~/Documents/Ansible-env/config:/etc/ansible
		command: tail -f /dev/null
	web:
		build:
			context: .
			dockerfile: ./docker/server.Dockerfile
	db:
		build:
			context: .
			dockerfile: ./docker/server.Dockerfile
	lb:
		build:
			context: .
			dockerfile: ./docker/server.Dockerfile
	ports:
		- 8080:80
			 

