version: '3'
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0b8e18f (add script)
services:
  master:
    build:
      context: .
      dockerfile: ./docker/master.Dockerfile
    image: ansible-master:latest
    working_dir: /root/ansible-dir
    container_name: ansible-master
    volumes:
      - ~/Documents/Ansible-env/medium_ansible:/root/ansible-dir
    command: tail -f /dev/null
=======
<<<<<<< HEAD
=======
>>>>>>> 2064af3 (ajout du docker-compose)
=======
>>>>>>> 0b8e18f (add script)

services:
	master:
		build:
			context: .
			dockerfile: ./docker/master.Dockerfile
		working_dir: /root/ansible
		volumes:
			- ~/Document/Ansible-env/medium_ansible/:/root/ansible
		
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 2064af3 (ajout du docker-compose)
=======
services:
=======
services:
>>>>>>> 145d44e (modify composer for volumes and directories bind)
=======
>>>>>>> 2064af3 (ajout du docker-compose)
=======
services:
>>>>>>> 0b8e18f (add script)
  master:
    build:
      context: .
      dockerfile: ./docker/master.Dockerfile
    image: ansible-master:latest
    working_dir: /root/ansible-dir
    container_name: ansible-master
    volumes:
      - ~/Documents/Ansible-env/medium_ansible:/root/ansible-dir
    command: tail -f /dev/null
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 145d44e (modify composer for volumes and directories bind)
=======
>>>>>>> 2064af3 (ajout du docker-compose)
=======
=======
>>>>>>> 0b8e18f (add script)
>>>>>>> 145d44e (modify composer for volumes and directories bind)
