version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./docker/master.Dockerfile
    image: ansible-master:latest
    working_dir: /root/ansible-dir
    container_name: ansible-master
    volumes:
      - ~/Documents/Ansible-env/medium_ansible:/root/ansible-dir
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true
    command: tail -f /dev/null
